// Generated by CoffeeScript 1.9.0
(function() {
  var Calculator;

  Calculator = (function() {
    function Calculator() {
      console.log("Instantiated new Calculator instance");
    }

    Calculator.prototype.add = function(num1, num2) {
      return num1 + num2;
    };

    Calculator.prototype.saySomething = function() {
      return alert("Hello, CoffeeScript 2!");
    };

    return Calculator;

  })();

  new Calculator().saySomething();

}).call(this);
